apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
  namespace: uat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-end
      type: frontend
  template:
    metadata:
      labels:
        app: front-end
        type: frontend
    spec:
      containers:
        - name: front-end
          image: azusctruatacr.azurecr.io/frontend:uat_v0.0.1
          envFrom:
            - configMapRef:
                name: uat-fe-env-config
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
          resources:
            requests:
              memory: 100Mi
              cpu: 10m
            limits:
              memory: 200Mi
              cpu: 20m
      nodeSelector:
        workload: uat
