// Data Model Types
type SurveyElement = {
  type: string;
  name: string;
  title?: string;
  placeholder?: string;
  rateType?: string;
  displayMode?: string;
  rateValues?: Array<{ value: number; text?: string }> | number[];
  minRateDescription?: string;
  maxRateDescription?: string;
  isRequired?: boolean;
  html?: string;
  choices?: string[] | Array<{ value: string; text: string }>;
  labelTrue?: string;
  labelFalse?: string;
  showCommentArea?: boolean;
  api?: string;
  autoGenerate?: boolean;
  minDecriptionValue?: string;
  maxDecriptionValue?: string;
  rateMax?: number;
  text?: string;
};

type SurveyPage = {
  name: string;
  description?: string;
  elements: SurveyElement[];
};

export type SurveyJson = {
  title?: string;
  pages?: SurveyPage[];
  elements?: Array<object>;
  showProgressBar?: string;
  progressBarType: string;
  completeText: string;
};

// CSS Types
export type SurveyNavigationCss = {
  complete: string;
  prev: string;
  next: string;
  start: string;
  preview: string;
  edit: string;
};

export type SurveyPanelCss = {
  contentEnter: string;
  contentLeave: string;
  enter: string;
  leave: string;
  asPage: string;
  number: string;
  title: string;
  titleExpandable: string;
  titleExpandableSvg: string;
  titleNumInline: string;
  titleExpanded: string;
  titleCollapsed: string;
  titleDisabled: string;
  titleOnExpand: string;
  titleOnError: string;
  titleBar: string;
  description: string;
  container: string;
  withFrame: string;
  content: string;
  icon: string;
  iconExpanded: string;
  footer: string;
  requiredText: string;
  header: string;
  collapsed: string;
  expanded: string;
  expandable: string;
  expandableAnimating: string;
  nested: string;
  invisible: string;
  navigationButton: string;
  compact: string;
  errorsContainer: string;
};

export type SurveyPanelDynamicTabsCss = {
  item: string;
  itemPressed: string;
  itemAsIcon: string;
  itemIcon: string;
  itemTitle: string;
};

export type SurveyPanelDynamicCss = {
  mainRoot: string;
  empty: string;
  root: string;
  iconRemove: string;
  navigation: string;
  title: string;
  header: string;
  headerTab: string;
  button: string;
  buttonRemove: string;
  buttonAdd: string;
  buttonPrev: string;
  buttonPrevDisabled: string;
  buttonNextDisabled: string;
  buttonNext: string;
  progressContainer: string;
  progress: string;
  progressBar: string;
  nested: string;
  progressText: string;
  separator: string;
  panelWrapper: string;
  footer: string;
  panelFooter: string;
  footerButtonsContainer: string;
  panelsContainer: string;
  panelWrapperInRow: string;
  panelWrapperEnter: string;
  panelWrapperLeave: string;
  panelWrapperList: string;
  progressBtnIcon: string;
  noEntriesPlaceholder: string;
  compact: string;
  tabsRoot: string;
  tabsLeft: string;
  tabsRight: string;
  tabsCenter: string;
  tabs: SurveyPanelDynamicTabsCss;
};

export type SurveyPageCss = {
  root: string;
  emptyHeaderRoot: string;
  title: string;
  description: string;
  number: string;
  errorsContainer: string;
};

export type SurveyQuestionCss = {
  contentEnter: string;
  contentLeave: string;
  enter: string;
  leave: string;
  mobile: string;
  mainRoot: string;
  flowRoot: string;
  withFrame: string;
  asCell: string;
  answered: string;
  header: string;
  headerLeft: string;
  headerTop: string;
  headerBottom: string;
  content: string;
  contentSupportContainerQueries: string;
  contentLeft: string;
  titleNumInline: string;
  titleLeftRoot: string;
  titleTopRoot: string;
  descriptionUnderInputRoot: string;
  titleBottomRoot: string;
  titleOnAnswer: string;
  titleEmpty: string;
  titleOnError: string;
  title: string;
  titleExpandable: string;
  titleExpandableSvg: string;
  titleExpanded: string;
  titleCollapsed: string;
  titleDisabled: string;
  titleReadOnly: string;
  titleBar: string;
  requiredText: string;
  number: string;
  description: string;
  descriptionUnderInput: string;
  comment: string;
  other: string;
  required: string;
  titleRequired: string;
  indent: number;
  footer: string;
  commentArea: string;
  formGroup: string;
  hasError: string;
  hasErrorTop: string;
  hasErrorBottom: string;
  collapsed: string;
  expandable: string;
  expandableAnimating: string;
  expanded: string;
  nested: string;
  invisible: string;
  composite: string;
  disabled: string;
  readOnly: string;
  preview: string;
  noPointerEventsMode: string;
  errorsContainer: string;
  errorsContainerTop: string;
  errorsContainerBottom: string;
};

export type SurveyImageCss = {
  mainRoot: string;
  root: string;
  image: string;
  adaptive: string;
  noImage: string;
  noImageSvgIconId: string;
  withFrame: string;
};

export type SurveyHtmlCss = {
  mainRoot: string;
  root: string;
  withFrame: string;
  nested: string;
};

export type SurveyErrorCss = {
  root: string;
  icon: string;
  item: string;
  locationTop: string;
  locationBottom: string;
};

export type SurveyCheckboxCss = {
  root: string;
  rootMobile: string;
  rootRow: string;
  rootMultiColumn: string;
  item: string;
  itemEnter: string;
  itemLeave: string;
  itemOnError: string;
  itemSelectAll: string;
  itemNone: string;
  itemDisabled: string;
  itemReadOnly: string;
  itemPreview: string;
  itemPreviewSvgIconId: string;
  itemChecked: string;
  itemHover: string;
  itemInline: string;
  label: string;
  labelChecked: string;
  itemControl: string;
  itemDecorator: string;
  itemSvgIconId: string;
  controlLabel: string;
  materialDecorator: string;
  other: string;
  column: string;
};

export type SurveyRadioGroupCss = {
  root: string;
  rootMobile: string;
  rootRow: string;
  rootMultiColumn: string;
  item: string;
  itemOnError: string;
  itemInline: string;
  label: string;
  labelChecked: string;
  itemEnter: string;
  itemLeave: string;
  itemDisabled: string;
  itemReadOnly: string;
  itemPreview: string;
  itemPreviewSvgIconId: string;
  itemChecked: string;
  itemHover: string;
  itemControl: string;
  itemDecorator: string;
  controlLabel: string;
  materialDecorator: string;
  other: string;
  clearButton: string;
  column: string;
};

export type SurveyBooleanCss = {
  mainRoot: string;
  root: string;
  rootRadio: string;
  item: string;
  itemOnError: string;
  control: string;
  itemChecked: string;
  itemExchanged: string;
  itemIndeterminate: string;
  itemDisabled: string;
  itemReadOnly: string;
  itemPreview: string;
  itemHover: string;
  label: string;
  labelTrue: string;
  labelFalse: string;
  switch: string;
  disabledLabel: string;
  labelReadOnly: string;
  labelPreview: string;
  sliderText: string;
  slider: string;
  sliderGhost: string;
  radioItem: string;
  radioItemChecked: string;
  radioItemDisabled: string;
  radioItemReadOnly: string;
  radioItemPreview: string;
  itemPreviewSvgIconId: string;
  radioLabel: string;
  radioControlLabel: string;
  radioFieldset: string;
  itemRadioDecorator: string;
  materialRadioDecorator: string;
  itemRadioControl: string;
  rootCheckbox: string;
  checkboxItem: string;
  checkboxLabel: string;
  checkboxItemOnError: string;
  checkboxItemIndeterminate: string;
  checkboxItemChecked: string;
  checkboxItemDecorator: string;
  checkboxItemDisabled: string;
  checkboxItemReadOnly: string;
  checkboxItemPreview: string;
  controlCheckbox: string;
  checkboxMaterialDecorator: string;
  checkboxControlLabel: string;
  svgIconCheckedId: string;
};

export type SurveyTextCss = {
  root: string;
  small: string;
  controlDisabled: string;
  controlReadOnly: string;
  controlPreview: string;
  constrolWithCharacterCounter: string;
  characterCounterBig: string;
  content: string;
  remainingCharacterCounter: string;
  onError: string;
};

export type SurveyMultipleTextCss = {
  root: string;
  rootMobile: string;
  itemLabel: string;
  itemLabelReadOnly: string;
  itemLabelDisabled: string;
  itemLabelPreview: string;
  itemLabelOnError: string;
  itemLabelAllowFocus: string;
  itemLabelAnswered: string;
  itemWithCharacterCounter: string;
  item: string;
  itemTitle: string;
  content: string;
  row: string;
  cell: string;
  cellError: string;
  cellErrorTop: string;
  cellErrorBottom: string;
};

export type SurveyDropdownCss = {
  root: string;
  popup: string;
  small: string;
  selectWrapper: string;
  other: string;
  onError: string;
  label: string;
  itemEnter: string;
  itemLeave: string;
  item: string;
  itemDisabled: string;
  itemChecked: string;
  itemHover: string;
  itemControl: string;
  itemDecorator: string;
  cleanButton: string;
  cleanButtonSvg: string;
  cleanButtonIconId: string;
  chevronButton: string;
  chevronButtonSvg: string;
  chevronButtonIconId: string;
  control: string;
  controlInputFieldComponent: string;
  controlValue: string;
  controlDisabled: string;
  controlReadOnly: string;
  controlPreview: string;
  controlEmpty: string;
  controlLabel: string;
  filterStringInput: string;
  materialDecorator: string;
  hintPrefix: string;
  hintSuffix: string;
};

export type SurveyImagePickerCss = {
  mainRoot: string;
  root: string;
  rootColumn: string;
  item: string;
  itemOnError: string;
  itemInline: string;
  itemChecked: string;
  itemDisabled: string;
  itemReadOnly: string;
  itemPreview: string;
  itemHover: string;
  label: string;
  itemDecorator: string;
  imageContainer: string;
  itemControl: string;
  image: string;
  itemText: string;
  other: string;
  itemNoImage: string;
  itemNoImageSvgIcon: string;
  itemNoImageSvgIconId: string;
  column: string;
  checkedItemDecorator: string;
  checkedItemSvgIcon: string;
  checkedItemSvgIconId: string;
};

export type SurveyMatrixCss = {
  mainRoot: string;
  tableWrapper: string;
  root: string;
  columnsAutoWidth: string;
  noHeader: string;
  rootVerticalAlignTop: string;
  rootVerticalAlignMiddle: string;
  rootAlternateRows: string;
  rowError: string;
  cell: string;
  row: string;
  rowDisabled: string;
  rowReadOnly: string;
  headerCell: string;
  rowTextCell: string;
  label: string;
  itemOnError: string;
  itemValue: string;
  itemChecked: string;
  itemDisabled: string;
  itemReadOnly: string;
  itemPreview: string;
  itemPreviewSvgIconId: string;
  itemHover: string;
  materialDecorator: string;
  itemDecorator: string;
  cellText: string;
  cellTextSelected: string;
  cellTextDisabled: string;
  cellResponsiveTitle: string;
  compact: string;
};

export type SurveyMatrixDropdownCss = {
  mainRoot: string;
  rootScroll: string;
  root: string;
  columnsAutoWidth: string;
  noHeader: string;
  hasFooter: string;
  rootVerticalAlignTop: string;
  rootVerticalAlignMiddle: string;
  tableWrapper: string;
  rootAlternateRows: string;
  cell: string;
  cellResponsiveTitle: string;
  errorsCell: string;
  errorsCellTop: string;
  errorsCellBottom: string;
  itemCell: string;
  row: string;
  rowDelayedEnter: string;
  rowEnter: string;
  rowLeave: string;
  expandedRow: string;
  rowHasPanel: string;
  rowHasEndActions: string;
  headerCell: string;
  rowTextCell: string;
  footerCell: string;
  footerTotalCell: string;
  columnTitleCell: string;
  cellRequiredText: string;
  detailButton: string;
  detailButtonExpanded: string;
  detailIcon: string;
  detailIconExpanded: string;
  detailIconId: string;
  detailIconExpandedId: string;
  detailPanelCell: string;
  detailRowCell: string;
  actionsCellPrefix: string;
  actionsCell: string;
  actionsCellDrag: string;
  emptyCell: string;
  verticalCell: string;
  cellQuestionWrapper: string;
  compact: string;
};

export type SurveyMatrixDynamicCss = {
  mainRoot: string;
  rootScroll: string;
  empty: string;
  root: string;
  columnsAutoWidth: string;
  noHeader: string;
  hasFooter: string;
  tableWrapper: string;
  rootAlternateRows: string;
  content: string;
  cell: string;
  cellResponsiveTitle: string;
  row: string;
  rowDelayedEnter: string;
  rowEnter: string;
  rowLeave: string;
  rowHasPanel: string;
  rowHasEndActions: string;
  expandedRow: string;
  itemCell: string;
  headerCell: string;
  rowTextCell: string;
  footerCell: string;
  columnTitleCell: string;
  cellRequiredText: string;
  button: string;
  detailRow: string;
  detailButton: string;
  detailButtonExpanded: string;
  detailIcon: string;
  detailIconExpanded: string;
  detailIconId: string;
  detailIconExpandedId: string;
  detailPanelCell: string;
  detailRowCell: string;
  actionsCellPrefix: string;
  actionsCell: string;
  actionsCellDrag: string;
  buttonAdd: string;
  buttonRemove: string;
  iconAdd: string;
  iconRemove: string;
  dragElementDecorator: string;
  iconDragElement: string;
  footer: string;
  footerTotalCell: string;
  emptyRowsSection: string;
  iconDrag: string;
  ghostRow: string;
  draggedRow: string;
  emptyCell: string;
  verticalCell: string;
  cellQuestionWrapper: string;
  errorsCell: string;
  errorsCellTop: string;
  errorsCellBottom: string;
  compact: string;
};

export type SurveyRatingCss = {
  rootDropdown: string;
  root: string;
  rootWrappable: string;
  rootLabelsTop: string;
  rootLabelsBottom: string;
  rootLabelsDiagonal: string;
  item: string;
  itemOnError: string;
  itemHover: string;
  selected: string;
  itemStar: string;
  itemStarOnError: string;
  itemStarHover: string;
  itemStarSelected: string;
  itemStarDisabled: string;
  itemStarReadOnly: string;
  itemStarPreview: string;
  itemStarHighlighted: string;
  itemStarUnhighlighted: string;
  itemStarSmall: string;
  itemSmiley: string;
  itemSmileyOnError: string;
  itemSmileyHover: string;
  itemSmileySelected: string;
  itemSmileyDisabled: string;
  itemSmileyReadOnly: string;
  itemSmileyPreview: string;
  itemSmileyHighlighted: string;
  itemSmileyScaleColored: string;
  itemSmileyRateColored: string;
  itemSmileySmall: string;
  minText: string;
  itemText: string;
  maxText: string;
  itemDisabled: string;
  itemReadOnly: string;
  itemPreview: string;
  itemFixedSize: string;
  control: string;
  itemSmall: string;
  selectWrapper: string;
  controlValue: string;
  controlDisabled: string;
  controlReadOnly: string;
  controlPreview: string;
  controlEmpty: string;
  filterStringInput: string;
  chevronButton: string;
  chevronButtonSvg: string;
  chevronButtonIconId: string;
  popup: string;
  onError: string;
};

export type SurveyCommentCss = {
  root: string;
  small: string;
  controlDisabled: string;
  controlReadOnly: string;
  controlPreview: string;
  content: string;
  remainingCharacterCounter: string;
  onError: string;
};

export type SurveyFileCss = {
  root: string;
  rootDragging: string;
  rootAnswered: string;
  rootDisabled: string;
  rootReadOnly: string;
  rootPreview: string;
  other: string;
  placeholderInput: string;
  previewItem: string;
  fileSign: string;
  fileList: string;
  fileSignBottom: string;
  dragArea: string;
  dragAreaActive: string;
  fileDecorator: string;
  onError: string;
  fileDecoratorDrag: string;
  fileInput: string;
  noFileChosen: string;
  chooseFile: string;
  chooseFileAsText: string;
  chooseFileAsTextDisabled: string;
  chooseFileAsIcon: string;
  chooseFileIconId: string;
  disabled: string;
  controlDisabled: string;
  removeButton: string;
  removeButtonBottom: string;
  removeButtonIconId: string;
  removeFile: string;
  removeFileSvg: string;
  removeFileSvgIconId: string;
  wrapper: string;
  defaultImage: string;
  defaultImageIconId: string;
  leftIconId: string;
  rightIconId: string;
  removeFileButton: string;
  dragAreaPlaceholder: string;
  imageWrapper: string;
  imageWrapperDefaultImage: string;
  single: string;
  singleImage: string;
  mobile: string;
  videoContainer: string;
  contextButton: string;
  video: string;
  actionsContainer: string;
  closeCameraButton: string;
  changeCameraButton: string;
  takePictureButton: string;
  loadingIndicator: string;
  page: string;
};

export type SurveySignaturePadCss = {
  mainRoot: string;
  root: string;
  small: string;
  controls: string;
  placeholder: string;
  canvas: string;
  backgroundImage: string;
  clearButton: string;
  clearButtonIconId: string;
  loadingIndicator: string;
};

export type SurveySaveDataCss = {
  root: string;
  rootWithButtons: string;
  info: string;
  error: string;
  success: string;
  button: string;
  shown: string;
};

export type SurveyWindowHeaderCss = {
  root: string;
  titleCollapsed: string;
  buttonsContainer: string;
  button: string;
  buttonExpanded: string;
  buttonCollapsed: string;
  collapseButton: string;
  closeButton: string;
  fullScreenButton: string;
};

export type SurveyWindowCss = {
  root: string;
  rootCollapsedMod: string;
  rootFullScreenMode: string;
  rootContent: string;
  body: string;
  header: SurveyWindowHeaderCss;
};

export type SurveyRankingCss = {
  root: string;
  rootMobileMod: string;
  rootDragMod: string;
  rootDisabled: string;
  rootReadOnly: string;
  rootPreview: string;
  rootDesignMode: string;
  rootDragHandleAreaIcon: string;
  rootSelectToRankMod: string;
  rootSelectToRankEmptyValueMod: string;
  rootSelectToRankAlignVertical: string;
  rootSelectToRankAlignHorizontal: string;
  rootSelectToRankSwapAreas: string;
  item: string;
  itemContent: string;
  itemIndex: string;
  itemIndexEmptyMode: string;
  itemDisabled: string;
  itemReadOnly: string;
  itemPreview: string;
  controlLabel: string;
  itemGhostNode: string;
  itemIconContainer: string;
  itemIcon: string;
  itemIconHoverMod: string;
  itemIconFocusMod: string;
  itemGhostMod: string;
  itemDragMod: string;
  itemOnError: string;
  container: string;
  containerEmptyMode: string;
  containerFromMode: string;
  containerToMode: string;
  containerPlaceholder: string;
  containersDivider: string;
};

export type SurveyButtonGroupCss = {
  root: string;
  item: string;
  itemIcon: string;
  itemDecorator: string;
  itemCaption: string;
  itemHover: string;
  itemSelected: string;
  itemDisabled: string;
  itemControl: string;
};

export type SurveyListCss = {
  root: string;
  item: string;
  itemBody: string;
  itemSelected: string;
  itemFocused: string;
};

export type SurveyActionBarCss = {
  root: string;
  item: string;
  defaultSizeMode: string;
  smallSizeMode: string;
  itemPressed: string;
  itemAsIcon: string;
  itemIcon: string;
  itemTitle: string;
};

export type SurveyVariablesCss = {
  mobileWidth: string;
  themeMark: string;
};

export type SurveyTagboxCss = {
  root: string;
  popup: string;
  small: string;
  selectWrapper: string;
  other: string;
  onError: string;
  label: string;
  itemSvgIconId: string;
  item: string;
  itemDisabled: string;
  itemChecked: string;
  itemHover: string;
  itemControl: string;
  itemDecorator: string;
  itemEnter: string;
  itemLeave: string;
  cleanButton: string;
  cleanButtonSvg: string;
  cleanButtonIconId: string;
  cleanItemButton: string;
  cleanItemButtonSvg: string;
  cleanItemButtonIconId: string;
  chevronButton: string;
  chevronButtonSvg: string;
  chevronButtonIconId: string;
  control: string;
  controlValue: string;
  controlValueItems: string;
  placeholderInput: string;
  controlEditable: string;
  controlDisabled: string;
  controlReadOnly: string;
  controlPreview: string;
  controlEmpty: string;
  controlLabel: string;
  filterStringInput: string;
  materialDecorator: string;
  hint: string;
  hintPrefix: string;
  hintSuffix: string;
  hintSuffixWrapper: string;
};

export type SurveyCss = {
  root: string;
  rootProgress: string;
  rootMobile: string;
  rootAnimationDisabled: string;
  rootReadOnly: string;
  rootCompact: string;
  rootFitToContainer: string;
  rootWrapper: string;
  rootWrapperFixed: string;
  rootWrapperHasImage: string;
  rootBackgroundImage: string;
  container: string;
  header: string;
  bodyContainer: string;
  body: string;
  bodyWithTimer: string;
  clockTimerRoot: string;
  clockTimerRootTop: string;
  clockTimerRootBottom: string;
  clockTimerProgress: string;
  clockTimerProgressAnimation: string;
  clockTimerTextContainer: string;
  clockTimerMinorText: string;
  clockTimerMajorText: string;
  bodyEmpty: string;
  bodyLoading: string;
  footer: string;
  title: string;
  description: string;
  logo: string;
  logoImage: string;
  headerText: string;
  headerClose: string;
  navigationButton: string;
  bodyNavigationButton: string;
  completedPage: string;
  completedBeforePage: string;
  timerRoot: string;
  navigation: SurveyNavigationCss;
  panel: SurveyPanelCss;
  paneldynamic: SurveyPanelDynamicCss;
  progress: string;
  progressTop: string;
  progressBottom: string;
  progressBar: string;
  progressText: string;
  progressButtonsRoot: string;
  progressButtonsNumbered: string;
  progressButtonsFitSurveyWidth: string;
  progressButtonsContainerCenter: string;
  progressButtonsContainer: string;
  progressButtonsConnector: string;
  progressButtonsButton: string;
  progressButtonsButtonBackground: string;
  progressButtonsButtonContent: string;
  progressButtonsHeader: string;
  progressButtonsFooter: string;
  progressButtonsImageButtonLeft: string;
  progressButtonsImageButtonRight: string;
  progressButtonsImageButtonHidden: string;
  progressButtonsListContainer: string;
  progressButtonsList: string;
  progressButtonsListElementPassed: string;
  progressButtonsListElementCurrent: string;
  progressButtonsListElementNonClickable: string;
  progressButtonsPageTitle: string;
  progressButtonsPageDescription: string;
  progressTextInBar: string;
  page: SurveyPageCss;
  pageTitle: string;
  pageDescription: string;
  row: string;
  rowMultiple: string;
  rowCompact: string;
  rowEnter: string;
  rowDelayedEnter: string;
  rowLeave: string;
  rowReplace: string;
  pageRow: string;
  question: SurveyQuestionCss;
  image: SurveyImageCss;
  html: SurveyHtmlCss;
  error: SurveyErrorCss;
  checkbox: SurveyCheckboxCss;
  radiogroup: SurveyRadioGroupCss;
  boolean: SurveyBooleanCss;
  text: SurveyTextCss;
  multipletext: SurveyMultipleTextCss;
  dropdown: SurveyDropdownCss;
  imagepicker: SurveyImagePickerCss;
  matrix: SurveyMatrixCss;
  matrixdropdown: SurveyMatrixDropdownCss;
  matrixdynamic: SurveyMatrixDynamicCss;
  rating: SurveyRatingCss;
  comment: SurveyCommentCss;
  expression: string;
  file: SurveyFileCss;
  signaturepad: SurveySignaturePadCss;
  saveData: SurveySaveDataCss;
  window: SurveyWindowCss;
  ranking: SurveyRankingCss;
  buttongroup: SurveyButtonGroupCss;
  list: SurveyListCss;
  actionBar: SurveyActionBarCss;
  variables: SurveyVariablesCss;
  tagbox: SurveyTagboxCss;
};
