declare const classNames: {
  readonly formFieldContainer: 'formFieldContainer';
  readonly formInputLabelContainer: 'formInputLabelContainer';
  readonly formInputLabel: 'formInputLabel';
  readonly requiredAsterisk: 'requiredAsterisk';
  readonly formInput: 'formInput';
  readonly inputTextExtra: 'inputTextExtra';
  readonly formInputDefault: 'formInputDefault';
  readonly formInputReadOnly: 'formInputReadOnly';
  readonly formInputTextarea: 'formInputTextarea';
  readonly formDateInput: 'formDateInput';
  readonly formDateFilled: 'formDateFilled';
  readonly formDatePlaceholder: 'formDatePlaceholder';
  readonly formMultiSelectInput: 'formMultiSelectInput';
  readonly placeholder: 'placeholder';
  readonly formFileInput: 'formFileInput';
  readonly formFileInputIconContainer: 'formFileInputIconContainer';
  readonly formFileInputIcon: 'formFileInputIcon';
  readonly formFileInputText: 'formFileInputText';
  readonly formNumberInputContainer: 'formNumberInputContainer';
  readonly formNumberInput: 'formNumberInput';
  readonly inputAction: 'inputAction';
  readonly leftInputAction: 'leftInputAction';
  readonly rightInputAction: 'rightInputAction';
};
export = classNames;
