import { apiAuthEndpoint, apiOnboardingEndpoint, apiCreateProjectEndpoint, apiCreateProjectAIEndpoint, apiPaymentEndPoint, apiProjectInfraEndpoint } from './env';

const API = {
  auth: {
    login: `${apiAuthEndpoint}/api/v1/user/sign-in`,
    socialSignUpSingIn: `${apiAuthEndpoint}/api/v1/user/social-auth/google`,
    registerEmail: `${apiAuthEndpoint}/api/v1/user/email/create-otp`,
    verifyEmail: `${apiAuthEndpoint}/api/v1/user/email/verify-otp`,
    regsterClubEmail: `${apiAuthEndpoint}/api/v1/club/email/create-otp`,
    createNewPassowrd: `${apiAuthEndpoint}/api/v1/user/password/create`,
    registerPhone: `${apiAuthEndpoint}/api/v1/user/phone/create-otp`,
    verifyPhone: `${apiAuthEndpoint}/api/v1/user/phone/verify-otp`,
    forgotPassword: `${apiAuthEndpoint}/api/v1/user/forgot-password/create`,
    verifyOtp: `${apiAuthEndpoint}/api/v1/user/forgot-password/verify`,
    setNewPassword: `${apiAuthEndpoint}/api/v1/user/forgot-password/change`,
    resetPassword: `${apiAuthEndpoint}/api/v1/user/reset-password`,
    requestValidation: `${apiAuthEndpoint}/api/v1/requests/validation`,
    checkAdmin: `${apiOnboardingEndpoint}/api/v1/groups/check-admin`,
    validateFlexTernEmail: `${apiAuthEndpoint}/api/v1/flextern/email/check`,
    flexternValues: `${apiAuthEndpoint}/api/v1/flextern/values`,
  },
  static: {
    talentRoles: `${apiAuthEndpoint}/api/v1/static/talent-role`,
    languages: `${apiAuthEndpoint}/api/v1/static/language/all`,
    countries: `${apiAuthEndpoint}/api/v1/static/country`,
    states: `${apiAuthEndpoint}/api/v1/static/state-by-id`,
    cities: `${apiAuthEndpoint}/api/v1/static/city`,
    institutes: `${apiAuthEndpoint}/api/v1/static/institute/all`,
    paginatedInstitutes: `${apiAuthEndpoint}/api/v1/static/institute/paginated`,
    educations: `${apiAuthEndpoint}/api/v1/static/education/all`,
    tools: `${apiAuthEndpoint}/api/v1/static/tools/all`,
    toolsAI: `${apiAuthEndpoint}/api/v1/static/tools/search-by-name`,
    skills: `${apiAuthEndpoint}/api/v1/static/skills/all`,
    skillsAI: `${apiAuthEndpoint}/api/v1/static/skills/search-by-name`,
    certificates: `${apiAuthEndpoint}/api/v1/static/certificates/all`,
    timezones: `${apiAuthEndpoint}/api/v1/static/timezone/all`,
    currencies: `${apiAuthEndpoint}/api/v1/static/currency/all`,
    companyIndustries: `${apiAuthEndpoint}/api/v1/static/company-industry/all`,
    projectAreas: `${apiAuthEndpoint}/api/v1/static/project-area/all`,
    services: `${apiAuthEndpoint}/api/v1/static/services/all`,
    disputeTypes: `${apiAuthEndpoint}/api/v1/static/dispute-type/all`,
    ratingTags: `${apiAuthEndpoint}/api/v1/static/tags/filter`,
    issueTypes: `${apiAuthEndpoint}/api/v1/support-issue-types`,
  },
  talentOnboarding: {
    userDetails: `${apiAuthEndpoint}/api/v1/user/details`,
    resumeParsedDetails: `${apiCreateProjectAIEndpoint}/api/v1/parse-resume`,
    updateResumeParsedDetails: `${apiCreateProjectAIEndpoint}/api/v1/parsed`,
    deleteResume: `${apiAuthEndpoint}/api/v1/talent/resume`,
    accountDetails: `${apiAuthEndpoint}/api/v1/talent/account-details`,
    profileDetails: `${apiAuthEndpoint}/api/v1/talent/profile-details`,
    checkpointComplete: `${apiAuthEndpoint}/api/v1/user/checkpoint/complete`,
    profileImageUpload: `${apiAuthEndpoint}/api/v1/user/profile/image-url`,
    profileResumeUpload: `${apiAuthEndpoint}/api/v1/talent/resume`,
    identityUpload: `${apiAuthEndpoint}/api/v1/flextern/identity/verification`,
    identityDelete: `${apiAuthEndpoint}/api/v1/flextern/identity/verification`,
    profileCompletionFlextern: `${apiAuthEndpoint}/api/v1/flextern/profile-percentage`
  },
  clientOnboarding: {
    accountDetails: `${apiAuthEndpoint}/api/v1/client/account-details`,
    profileDetails: `${apiAuthEndpoint}/api/v1/client/profile-details`,
  },
  profile: {
    talent: `${apiOnboardingEndpoint}/api/v1/talent/details`,
    talentProjects: `${apiOnboardingEndpoint}/api/v1/talent/get-recommanded-projects`,
    client: `${apiOnboardingEndpoint}/api/v1/client/details`,
    clientProjects: `${apiOnboardingEndpoint}/api/v1/client/completed-projects`,
    addToFav: `${apiOnboardingEndpoint}/api/v1/favourite/set-user`,
    removeFav: `${apiOnboardingEndpoint}/api/v1/favourite/remove`,
    addToFavProject: `${apiOnboardingEndpoint}/api/v1/favourite/set-project`,
    addToFavProjectFlextern: `${apiOnboardingEndpoint}/api/v2/favourite/set-project`,
    addToFavTeam: `${apiOnboardingEndpoint}/api/v1/favourite/set-team`,
    recentProjects: `${apiOnboardingEndpoint}/api/v1/users/completed-projects`,
    reviews: `${apiOnboardingEndpoint}/api/v1/users/reviews`,
    report: `${apiAuthEndpoint}/api/v1/user/report`,
    publicTeamMembers: `${apiOnboardingEndpoint}/api/v1/team-members`,
  },
  dashboard: {
    userData: `${apiAuthEndpoint}/api/v1/user/details`,
    totalReferralAmount: `${apiAuthEndpoint}/api/v1/referrals/amount`,
    recommendedProjects: `${apiOnboardingEndpoint}/api/v1/talent/get-recommended-projects`,
    profilePercentage: `${apiAuthEndpoint}/api/v1/user/profile-percentage`,
    checkBidsAccepted: `${apiOnboardingEndpoint}/api/v1/marketplace/list-bid-projects`,
    getProjectDetails: `${apiCreateProjectEndpoint}/api/v1/common/project/info`,

    // report
    reportEntity: `${apiAuthEndpoint}/api/v1/support-request`,
    checkIfReported: `${apiAuthEndpoint}/api/v1/check-report-submission`,

    // team
    getTeamMember: `${apiOnboardingEndpoint}/api/v1/teams/get-members`,
    getInvitedMember: `${apiOnboardingEndpoint}/api/v1/teams/invited-members-new`,
    recommendedProjectsTeam: `${apiOnboardingEndpoint}/api/v1/teams/recommended-projects`,

    joinRequest: `${apiOnboardingEndpoint}/api/v1/teams/join-requests`,
    recommendedTalent: `${apiOnboardingEndpoint}/api/v1/teams/recommended-talents`,
    validateUrl: `${apiAuthEndpoint}/api/v1/team/invite-member/validate-deep-link`,
    updateInvitation: `${apiAuthEndpoint}/api/v1/team/invite-member/update-invite`,
    removeMember: `${apiAuthEndpoint}/api/v1/team/delete-member`,
    teamProfilePercentage: `${apiOnboardingEndpoint}/api/v1/teams/profile-percentage`,
    activeProjectsForTeam: `${apiOnboardingEndpoint}/api/v1/teams/active-projects`,
    upcomingProjectsForTeam: `${apiOnboardingEndpoint}/api/v1/teams/upcoming-projects`,

    // talent
    recommendedTeams: `${apiOnboardingEndpoint}/api/v1/talent/get-recommended-teams`,
    teamInvitaion: `${apiOnboardingEndpoint}/api/v1/talent/team-invite-new`,
    projectInvite: `${apiOnboardingEndpoint}/api/v1/talent/team-project-invite`,
    getMyTeam: `${apiOnboardingEndpoint}/api/v1/talent/my-teams`,
    projectInvites: `${apiOnboardingEndpoint}/api/v1/user/alerts/invitations`,
    activeProjectsForTalent: `${apiOnboardingEndpoint}/api/v1/talent/active-projects`,
    upcomingProjectsForTalent: `${apiOnboardingEndpoint}/api/v1/talent/upcoming-projects`,

    // client
    activeProjectsForClient: `${apiOnboardingEndpoint}/api/v1/client/active-projects`,
    upcomingProjectsForClient: `${apiOnboardingEndpoint}/api/v1/client/upcoming-projects`,
    projectsBidsForClient: `${apiOnboardingEndpoint}/api/v1/client/open-listing`,
    recommendedTeamsForClient: `${apiOnboardingEndpoint}/api/v1/client/recommended-teams`,
    updateCardStatus: `${apiOnboardingEndpoint}/api/v1/alert/mark-as-read`,

    // files
    downloadUrl: `${apiCreateProjectEndpoint}/api/v1/download/url`,
  },
  delegate: {
    inviteDelegate: `${apiAuthEndpoint}/api/v1/invitation/delegate`,
    signUpDelegate: `${apiAuthEndpoint}/api/v1/user/delegate/signup`,
    delegateInvitationStatus: `${apiAuthEndpoint}/api/v1/invitation/delegate/status`,
  },
  createProject: {
    createProject: `${apiCreateProjectEndpoint}/api/v1/project/create`,
    createProjectAI: `${apiCreateProjectAIEndpoint}/api/v1/short_product_requirements`,
    bestTalents: `${apiCreateProjectEndpoint}/api/v1/project/best-talents`,
    favoriteTalents: `${apiCreateProjectEndpoint}/api/v1/project/favorite-talents`,
    favoriteTeams: `${apiAuthEndpoint}/api/v1/client/favourites`,
    almaMaterTalents: `${apiCreateProjectEndpoint}/api/v1/project/alma-mater-talents`,
    inviteTalents: `${apiCreateProjectEndpoint}/api/v1/project/invite-talents`,
    projectFileUpload: `${apiCreateProjectEndpoint}/api/v1/project/file`,
    saveDraftProject: `${apiCreateProjectEndpoint}/api/v1/project/draft/save`,
    draftProjectsCheck: `${apiCreateProjectEndpoint}/api/v1/project/draft/check`,
    deleteDraftProject: `${apiCreateProjectEndpoint}/api/v1/project/draft`,
  },
  projectDetails: {
    getProjectDetails: `${apiCreateProjectEndpoint}/api/v1/common/project/info`,
    getProjectTeamMember: `${apiCreateProjectEndpoint}/api/v1/project-course/assigned-roles`,
    getReceivedBids: `${apiCreateProjectEndpoint}/api/v1/bid/selection/list-bids`,
    getBidReview: `${apiCreateProjectEndpoint}/api/v1/bid/selection/review-bid`,
    assignBid: `${apiCreateProjectEndpoint}/api/v1/bid/selection/assign-bid`,
    commonBidInfo: `${apiCreateProjectEndpoint}/api/v1/common/bid/info`,
    commonBidInfoPublic: `${apiCreateProjectEndpoint}/api/v1/common/bid/info/public`,
    unassignRole: `${apiCreateProjectEndpoint}/api/v1/project-course/unassigned-roles`,
    accept: `${apiAuthEndpoint}/api/v1/invitation/accept`, // put invite id
    reject: `${apiAuthEndpoint}/api/v1/invitation/reject`, // put invite id
    getInvitaion: `${apiAuthEndpoint}/api/v1/invitation`,
    getSentInvitaion: `${apiAuthEndpoint}/api/v1/invitations/sent`,
    removeWorker: `${apiCreateProjectEndpoint}/api/v1/project-course/workers`,
    requests: `${apiAuthEndpoint}/api/v1/requests`,
    terminateProject: `${apiCreateProjectEndpoint}/api/v1/project/termination`,
    withdrawProject: `${apiCreateProjectEndpoint}/api/v1/withdraw-project`,
    relistProject: `${apiCreateProjectEndpoint}/api/v1/project/relisting`,
    relistProjectByDate: `${apiCreateProjectEndpoint}/api/v1/project/relist-by-date`,
    requestChange: `${apiCreateProjectEndpoint}/api/v1/request-bid-changes`,
    rejectBidChange: `${apiCreateProjectEndpoint}/api/v1/reject-bid-changes`,
    acceptBidChange: `${apiCreateProjectEndpoint}/api/v1/accept-bid-changes`,
    getBidTimeline: `${apiCreateProjectEndpoint}/api/v1/bid-timeline`,
    getBidSnapshot: `${apiCreateProjectEndpoint}/api/v1/bid-snapshot`,
    downloadCertificate: `${apiCreateProjectEndpoint}/api/v1/project/certificate`,
    // contract flow
    checkDocumentActivated: `${apiCreateProjectEndpoint}/api/v1/legal/document/check`,
    getDocument: `${apiCreateProjectEndpoint}/api/v1/legal/document`,
    getDocumentTimeline: `${apiCreateProjectEndpoint}/api/v1/legal/document/timeline`,
    sendDocument: `${apiCreateProjectEndpoint}/api/v1/legal/document/send`,
    signContractByTalent: `${apiCreateProjectEndpoint}/api/v1/legal/document/sign`,
    terminateContract: `${apiCreateProjectEndpoint}/api/v1/legal/document/terminate`,
    updateContract: `${apiCreateProjectEndpoint}/api/v1/legal/document/update`,
    extendDocValidity: `${apiCreateProjectEndpoint}/api/v1/project/documents-validity-extension`,
    extendPaymentValidity: `${apiCreateProjectEndpoint}/api/v1/project/payment-validity-extension`,
    getActiveStage: `${apiCreateProjectEndpoint}/api/v1/bid/get_stage`,
    // invite get
    bestTalents: `${apiCreateProjectEndpoint}/api/v1/project-course/recommended-talents`,
    favoriteTalents: `${apiCreateProjectEndpoint}/api/v1/project-course/favorite-talents`,
    almaMaterTalents: `${apiCreateProjectEndpoint}/api/v1/project-course/alma-mater-talents`,
    // Project Infrastructure
    verifyInfraAccess: `${apiProjectInfraEndpoint}/api/v1/infra/verify-access`,
    getInfraData: `${apiProjectInfraEndpoint}/api/v1/infra`,
    createInfra: `${apiProjectInfraEndpoint}/api/v1/infra/create`,
    terminateInfra: `${apiProjectInfraEndpoint}/api/v1/infra/decommission`,

    getAppConfig: `${apiCreateProjectEndpoint}/api/v1/app_config`,
  },
  projectMilestones: {
    getProjectMilestones: `${apiCreateProjectEndpoint}/api/v1/project/milestones`,
    getProjectTransactionsForTalent: `${apiCreateProjectEndpoint}/api/v1/project/transactions-talent`,
    getProjectTransactionsForClient: `${apiCreateProjectEndpoint}/api/v1/project/transactions-client`,
    submitMilestone: `${apiCreateProjectEndpoint}/api/v1/project/milestones/submission`,
    acceptMilestone: `${apiCreateProjectEndpoint}/api/v1/project/milestones/acceptance`,
    projectFileUpload: `${apiCreateProjectEndpoint}/api/v1/milestone/file`,
    saveMilestone: `${apiCreateProjectEndpoint}/api/v1/project/milestones/update`,
    rejectMilestone: `${apiCreateProjectEndpoint}/api/v1/project/milestone/reject`,
    getSubmissionHistory: `${apiCreateProjectEndpoint}/api/v1/project/milestones/artifacts`,
    markComplete: `${apiCreateProjectEndpoint}/api/v1/project/milestones/complete`,
    getSingleMilestone: `${apiCreateProjectEndpoint}/api/v1/project/milestone`,
    getDisputes: `${apiCreateProjectEndpoint}/api/v1/project/disputes`,
    saveDraftMilestone: `${apiCreateProjectEndpoint}/api/v1/project/milestones/artifacts/save`,
    getDraftMilestone: `${apiCreateProjectEndpoint}/api/v1/project/milestones/artifacts/draft`,
    deleteDraftMilestone: `${apiCreateProjectEndpoint}/api/v1/project/milestones/artifacts/delete`,
  },
  inviteTeamMember: {
    bestTalents: `${apiAuthEndpoint}/api/v1/team/best-talents`,
    favoriteTalents: `${apiAuthEndpoint}/api/v1/team/favourite-talents`,
    almaMaterTalents: `${apiAuthEndpoint}/api/v1/team/alma-mater-talents`,
    sendInvitaion: `${apiAuthEndpoint}/api/v1/invitation/send`,
    getTeamMember: `${apiAuthEndpoint}/api/v1/team/members`,

    // Updated API to invite talent/team and for client
    requests: `${apiAuthEndpoint}/api/v1/requests`,
    validateRequest: `${apiAuthEndpoint}/api/v1/requests/validation`,

    // get status requests
    status: `${apiOnboardingEndpoint}/api/v1/request/get`,
    checkAdmin: `${apiOnboardingEndpoint}/api/v1/groups/check-admin`,
  },
  marketplace: {
    client: {
      cardInfo: `${apiOnboardingEndpoint}/api/v1/client/cards-info`,
      listProject: `${apiOnboardingEndpoint}/api/v1/client/list-projects`,
      listTalents: `${apiOnboardingEndpoint}/api/v1/client/list-talents`,
    },
    talent: {
      cardInfo: `${apiOnboardingEndpoint}/api/v1/talent/cards-info`,
      listProject: `${apiOnboardingEndpoint}/api/v1/talent/list-projects`,
      listClients: `${apiOnboardingEndpoint}/api/v1/talent/list-clients`,
    },
    cardInfo: `${apiOnboardingEndpoint}/api/v2/marketplace/cards-info`,
    listProject: `${apiOnboardingEndpoint}/api/v2/marketplace/list-projects`,
    listTalents: `${apiOnboardingEndpoint}/api/v2/marketplace/list-talents`,
    bidProjects: `${apiOnboardingEndpoint}/api/v1/marketplace/list-bid-projects`,
    receivedBids: `${apiOnboardingEndpoint}/api/v1/received-bids-projects`,
    myBids: `${apiOnboardingEndpoint}/api/v1/my-bids-projects`,
    listTeams: `${apiOnboardingEndpoint}/api/v1/marketplace/list-teams`,
    listClients: `${apiOnboardingEndpoint}/api/v1/marketplace/list-clients`,

    //v2
    cardInfoFlextern: `${apiOnboardingEndpoint}/api/v2/marketplace/cards-info`,
    listProjectFlextern: `${apiOnboardingEndpoint}/api/v2/marketplace/list-projects`,
    listTalentsFlextern: `${apiOnboardingEndpoint}/api/v2/marketplace/list-talents`,

    // internal
    allProjectsUrl: `${apiOnboardingEndpoint}/api/v1/marketplace/list-projects/all`,
  },
  globalSearch: {
    search: `${apiOnboardingEndpoint}/api/v1/search`,
  },
  notifications: {
    allNotifications: `${apiOnboardingEndpoint}/api/v1/notification/all`,
    alerts: `${apiOnboardingEndpoint}/api/v1/alerts`,
    subscribe: `${apiAuthEndpoint}/api/v1/user/subscribe`,
    unsubscribe: `${apiAuthEndpoint}/api/v1/user/unsubscribe`,
    polling: `${apiAuthEndpoint}/api/v1/notifications/polling`,
    markAsRead: `${apiAuthEndpoint}/api/v1/notifications/mark-as-read`,
    markAllAsRead: `${apiAuthEndpoint}/api/v1/notifications/mark-all-as-read`,
  },
  createBid: {
    checkBid: `${apiCreateProjectEndpoint}/api/v1/bid/check`,
    createBid: `${apiCreateProjectEndpoint}/api/v1/bid/create`,
    projectInfo: `${apiCreateProjectEndpoint}/api/v1/common/project/info`,
    bidInfo: `${apiCreateProjectEndpoint}/api/v1/bid/info`,
    roles: `${apiCreateProjectEndpoint}/api/v1/bid/roles`,
    setWorkers: `${apiCreateProjectEndpoint}/api/v1/bid/set-workers`,
    setMilestones: `${apiCreateProjectEndpoint}/api/v1/bid/set-milestones`,
    milestoneFileUpload: `${apiCreateProjectEndpoint}/api/v1/bid/file`,
    submitBid: `${apiCreateProjectEndpoint}/api/v1/bid/submit`,
    changeBidType: `${apiCreateProjectEndpoint}/api/v1/bid-type`,
    deleteDraftBid: `${apiCreateProjectEndpoint}/api/v1/bid/remove`,
  },
  team: {
    getTeam: `${apiOnboardingEndpoint}/api/v1/talent/my-teams`,
    teamById: `${apiOnboardingEndpoint}/api/v1/teams`,
    teamInfoById: `${apiAuthEndpoint}/api/v1/team`,
    create: `${apiAuthEndpoint}/api/v1/team/create`,
    update: `${apiAuthEndpoint}/api/v1/team/update`,
    createDraft: `${apiAuthEndpoint}/api/v1/team/draft/save`,
    checkDraft: `${apiAuthEndpoint}/api/v1/team/draft/check`,
    deleteDraft: `${apiAuthEndpoint}/api/v1/team/draft`,
    memberType: `${apiAuthEndpoint}/api/v1/team/member_type`,
    getInvitation: `${apiAuthEndpoint}/api/v1/requests`,
  },
  dispute: {
    paginatedProjects: `${apiCreateProjectEndpoint}/api/v1/disputes/project-names`,
    raiseDispute: `${apiCreateProjectEndpoint}/api/v1/disputes`,
    allDisputes: `${apiCreateProjectEndpoint}/api/v1/disputes`,
    acceptDispute: `${apiCreateProjectEndpoint}/api/v1/disputes/accept`,
    replyOnDispute: `${apiCreateProjectEndpoint}/api/v1/disputes/reply`,
    disputeReplies: `${apiCreateProjectEndpoint}/api/v1/disputes/replies`,
    disputeReplyFileUpload: `${apiCreateProjectEndpoint}/api/v1/dispute/file`,
    resolveDispute: `${apiCreateProjectEndpoint}/api/v1/disputes/resolve`,
    disputesCount: `${apiCreateProjectEndpoint}/api/v1/disputes/count`,
  },
  rating: {
    giveRating: `${apiCreateProjectEndpoint}/api/v1/ratings`,
    yourSubmittedRating: `${apiCreateProjectEndpoint}/api/v1/ratings/your-provided-rating`,
    yourRating: `${apiCreateProjectEndpoint}/api/v1/ratings/your-rating`,
  },
  myTeams: {
    cardInfo: `${apiOnboardingEndpoint}/api/v1/my-teams/cards-info`,
    listTeams: `${apiOnboardingEndpoint}/api/v1/my-teams/teams`,
    listInvites: `${apiOnboardingEndpoint}/api/v1/my-teams/invitations`,
    listJoinReq: `${apiOnboardingEndpoint}/api/v1/my-teams/join-requests`,
    listFav: `${apiOnboardingEndpoint}/api/v1/my-teams/favourites`,
    listTalents: `${apiOnboardingEndpoint}/api/v1/my-teams/my-talents`,
    listClients: `${apiOnboardingEndpoint}/api/v1/my-teams/my-clients`,
    listRecomm: `${apiOnboardingEndpoint}/api/v1/my-teams/recommended`,
  },
  project: {
    cardInfo: `${apiOnboardingEndpoint}/api/v1/projects-count`,
    projects: `${apiOnboardingEndpoint}/api/v1/projects`,
    ongoingProjects: `${apiOnboardingEndpoint}/api/v1/ongoing-projects`,
    upcomingProjects: `${apiOnboardingEndpoint}/api/v1/upcoming-projects`,
    comletedProjects: `${apiOnboardingEndpoint}/api/v1/completed-projects`,
    terminatedProjects: `${apiOnboardingEndpoint}/api/v1/terminated-projects`,
    disputedProjects: `${apiOnboardingEndpoint}/api/v1/disputed-projects`,
    invitedProjects: `${apiOnboardingEndpoint}/api/v1/invited-projects`,
    clientName: `${apiOnboardingEndpoint}/api/v1/projects/client-names`,
    teamName: `${apiOnboardingEndpoint}/api/v1/projects/team-names`,
  },
  payment: {
    taxInfo: `${apiPaymentEndPoint}/api/v1/tax-info`,
    createStripeAccount: `${apiPaymentEndPoint}/api/v1/payment-account`,
    linkStripeAccount: `${apiPaymentEndPoint}/api/v1/payment-account-link`,
    makeMilestonePayment: `${apiPaymentEndPoint}/api/v1/checkout-session`,
    applicationFee: `${apiPaymentEndPoint}/api/v1/settings/application-fee`,
    transferFunds: `${apiPaymentEndPoint}/api/v1/transfer-funds`,
    spendingDetails: `${apiOnboardingEndpoint}/api/v1/users/payments`,
    upcomingPayments: `${apiOnboardingEndpoint}/api/v1/users/upcoming-payments`,
    updatePaymentStatus: `${apiPaymentEndPoint}/api/v1/checkout-session-cancel`,
  },
  referralAndReward: {
    createReferrals: `${apiAuthEndpoint}/api/v1/referrals`,
    validateReferral: `${apiAuthEndpoint}/api/v1/referrals/validation`,
    convertReferral: `${apiAuthEndpoint}/api/v1/referrals/conversion`,
    allReferrals: `${apiAuthEndpoint}/api/v1/referrals`,
  },
  clubs: {
    listClubs: `${apiOnboardingEndpoint}/api/v1/clubs`,
    cardInfo: `${apiOnboardingEndpoint}/api/v1/clubs/card-info`,
  },
  paymentFullView: {
    paymentMetrics: `${apiOnboardingEndpoint}/api/v1/payment-metrics`,
    paymentHistory: `${apiOnboardingEndpoint}/api/v1/payment-history`,
  },
  fileUpload: {
    scan: `${apiCreateProjectEndpoint}/api/v1/file/scanning/status`,
  },
  assessments: {
    user_assessments: `${apiOnboardingEndpoint}/api/v1/candidate/assessments`,
    team_assessments: `${apiOnboardingEndpoint}/api/v1/assessment/teams-info`,
    all_assessments: `${apiOnboardingEndpoint}/api/v1/all/assessment/dropdown`,
    delete_assessment: `${apiOnboardingEndpoint}/api/v1/candidate/assessment`,
    toggle_assessment_hidden: `${apiOnboardingEndpoint}/api/v1/candidate/hide/assessment`,
    add_assessment: `${apiOnboardingEndpoint}/api/v1/add/candidate/assessment/list`,
    get_assessment_link: `${apiOnboardingEndpoint}/api/v1/candidate/assessment/link`,
    delete_non_assessment: `${apiOnboardingEndpoint}/api/v1/candidate/non-assessment`,
    prepopulate: `${apiOnboardingEndpoint}/api/v1/candidate/assessment/prepopulate`,
  },
  support: {
    create: `${apiAuthEndpoint}/api/v1/support-request`,
    count: `${apiAuthEndpoint}/api/v1/support-request/count`,
    list: `${apiAuthEndpoint}/api/v1/support-requests/paginated`,
    delete: `${apiAuthEndpoint}/api/v1/support-request`,
  },
  hiring: {
    show_hiring_tab: `${apiAuthEndpoint}/api/v1/talent/check-mandatory-onboarding-details`,
    questions_link: `${apiOnboardingEndpoint}/api/v1/coding-test/questions`,
  },

  // permissions
  permissions: {
    appPermissions: `${apiAuthEndpoint}/api/v1/app-component-permissions`,
  },
};

export default API;
export { apiAuthEndpoint };
