import { create } from 'zustand';
import {
  getIndividualOverview,
  getPerformanceChartData,
  getRecognitionChartData,
  getAiSummary,
  getTeamPerformanceSummary,
  getTeamLeaderboard,
  getTeamMembersDetails,
  getTeamRoles,
  getTeamPerformanceInsightsOverview,
  getTeamDiversity,
  getTeamMembersAttractivenessDetails,
  getTeamUniversities,
  getConversationParticipationFiles,
  getConversationParticipation,
  getCommits,
} from '../actions/analytics-actions';
import { TimePeriodOptions } from '../constraints/enums/analytics-enums';

const defaultInitState = {
  individualOverview: null,
  isIndividualOverviewLoading: false,
  projectsList: [],
  isProjectsListLoading: false,
  recognitionChartData: {
    chartData: [],
    chartConfig: {},
  },
  team: {
    performanceSummary: null,
    isPerformanceSummaryLoading: false,
    teamLeaderboard: null,
    isTeamLeaderboardLoading: false,
    teamMembersAttractivenessDetails: null,
    isTeamMembersAttractivenessDetailsLoading: false,
    teamRoles: null,
    isTeamRolesLoading: false,
    teamUniversities: null,
    isTeamUniversitiesLoading: false,
    teamDiversity: null,
    isTeamDiversityLoading: false,
    teamMembersDetails: null,
    isTeamMembersDetailsLoading: false,
    teamPerformanceInsightsOverview: null,
    isTeamPerformanceInsightsOverviewLoading: false,
  },
  isRecognitionChartDataLoading: false,
  performanceChartData: {
    chartData: [],
    chartConfig: {},
  },
  isPerformanceChartDataLoading: false,
  aiSummary: null,
  isAiSummaryLoading: false,
  thirdPartyAppsData: null,
  isThirdPartyAppsDataLoading: false,
  conversationParticipation: null,
  isConversationParticipationLoading: false,
  conversationParticipationFiles: null,
  isConversationParticipationFilesLoading: false,
  commits: null,
  isCommitsLoading: false,
  branchHistory: null,
  isBranchHistoryLoading: false,
};

export const useAnalyticsStore = create<any>((set) => ({
  ...defaultInitState,
  getRecognitionChartData: async (projectId: string, userId: string) => getRecognitionChartData(projectId, userId, set),
  getPerformanceChartData: async (projectId: string, userId: string) => getPerformanceChartData(projectId, userId, set),
  getAiSummary: async (projectId: string, userId: string) => getAiSummary(projectId, userId, set),
  getIndividualOverview: async (userId: string, projectId: string) => getIndividualOverview(userId, projectId, set),
  getTeamPerformanceSummary: async (projectId: string) => getTeamPerformanceSummary(projectId, set),
  getTeamMembersAttractivenessDetails: async (projectId: string) => getTeamMembersAttractivenessDetails(projectId, set),
  getTeamLeaderboard: async (projectId: string) => getTeamLeaderboard(projectId, set),
  getTeamRoles: async (projectId: string) => getTeamRoles(projectId, set),
  getTeamUniversities: async (projectId: string) => getTeamUniversities(projectId, set),
  getTeamDiversity: async (projectId: string) => getTeamDiversity(projectId, set),
  getTeamMembersDetails: async (projectId: string) => getTeamMembersDetails(projectId, set),
  getTeamPerformanceInsightsOverview: async (projectId: string) => getTeamPerformanceInsightsOverview(projectId, set),
  getConversationParticipation: async (
    projectId: string,
    userId: string,
    messagesCountState: TimePeriodOptions,
    participationPercentageState: TimePeriodOptions,
  ) => getConversationParticipation(projectId, userId, messagesCountState, participationPercentageState, set),
  getConversationParticipationFiles: async (projectId: string, userId: string) =>
    getConversationParticipationFiles(projectId, userId, set),
  getCommits: async (projectId: string, userId: string) => getCommits(projectId, userId, set),
}));
