name: Azure Static Web Apps CI/CD

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Enter name"
        required: true
        type: string

      option:
        description: "Select option"
        required: true
        type: choice
        options:
          - A
          - B
          - C

      city:
        description: "Enter city (required only if option A is selected)"
        required: false
        type: choice
        options:
          - x
          - y

# jobs:
#   build_and_deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Show inputs
#         run: |
#           echo "Name: ${{ github.event.inputs.name }}"
#           echo "Option: ${{ github.event.inputs.option }}"
#           echo "City: ${{ github.event.inputs.city }}"

#       - name: Validate city input for option A
#         if: ${{ github.event.inputs.option == 'A' && github.event.inputs.city == '' }}
#         run: |
#           echo "Error: You must specify a city when option A is selected."
#           exit 1

#       - name: Continue deployment
#         run: echo "Proceeding with deployment for option ${{ github.event.inputs.option }}"


jobs:
  build_and_deploy_job:
    #if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      # - name: Install Dependencies
      #   run: |
      #     npm install --legacy-peer-deps && npm install --save env-cmd --legacy-peer-deps

      # - name: NPM Build
      #   run: |
      #     npm run build -- --mode ${{ env.VITE_ENV_MODE }}
      
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_BEACH_0CA3A9B0F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          skip_api_build: true
          skip_app_build: true
          app_location: '.'
          output_location: ''
          is_static_export: true
          ###### End of Repository/Build Configurations ######

  # close_pull_request_job:
  #   if: github.event_name == 'pull_request' && github.event.action == 'closed'
  #   runs-on: ubuntu-latest
  #   name: Close Pull Request Job
  #   steps:
  #     - name: Close Pull Request
  #       id: closepullrequest
  #       uses: Azure/static-web-apps-deploy@v1
  #       with:
  #         azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_BEACH_0CA3A9B0F }}
  #         action: "close"
