name: Tag Dispatch & Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Target branch to push the tag'
        required: true
        type: choice
        options:
          - uat
          - production
      version_type:
        description: 'Release version'
        required: true
        type: choice
        options:
          - major
          - minor
          - patch
      tag_pattern:
        description: 'Tag pattern for the selected branch'
        required: true
        type: choice
        options:
          - uat_*
          - tru-uat_*
          - v*
          - tru-prod_v*

jobs:
  tag-dispatch:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ github.event.inputs.branch }}
        submodules: true

    - name: Fetch tags
      run: git fetch --tags

    - name: Current branch
      run: git branch

    - name: Get Latest Tag
      id: get_latest_tag
      run: |
        branch=${{ github.event.inputs.branch }}
        tag_pattern=${{ github.event.inputs.tag_pattern }}

        if [ "$branch" = "production" ]; then
          if [[ "$tag_pattern" != "v*" && "$tag_pattern" != "tru-prod_v*" ]]; then
            echo "Invalid tag pattern for production branch. Use 'v*' or 'tru-prod_v*'."
            exit 1
          fi
        elif [ "$branch" = "uat" ]; then
          if [[ "$tag_pattern" != "uat_*" && "$tag_pattern" != "tru-uat_*" ]]; then
            echo "Invalid tag pattern for uat branch. Use 'uat_*' or 'tru-uat_*'."
            exit 1
          fi
        fi

        TAG=$(git tag -l "$tag_pattern" | sort -V --reverse | sed -n 1p)
        echo "latest_tag=$TAG" >> $GITHUB_ENV
        [[ -z "${TAG}" ]] && echo "No tag found..." || echo "Tag found: ${TAG}"

    - name: Increment Tag
      id: increment_tag
      run: |
        latest_tag=${{ env.latest_tag }}
        version_type=${{ github.event.inputs.version_type }}
        
        if [ -z "$latest_tag" ]; then
          echo "No previous tag found. Exiting."
          exit 1
        fi
        
        # Extract the prefix and version number
        prefix="${latest_tag%%v*}"  # Extract everything before 'v'
        version="${latest_tag#${prefix}v}"  # Extract everything after 'prefixv'
        
        IFS='.' read -r -a version_parts <<< "$version"
        
        major=${version_parts[0]}
        minor=${version_parts[1]}
        patch=${version_parts[2]}
        
        case $version_type in
          major)
            major=$((major + 1))
            minor=0
            patch=0
            ;;
          minor)
            minor=$((minor + 1))
            patch=0
            ;;
          patch)
            patch=$((patch + 1))
            ;;
        esac
        
        new_tag="${prefix}v${major}.${minor}.${patch}"
        
        echo "next_tag=$new_tag" >> $GITHUB_ENV
        echo "Next tag: $new_tag"

    - name: Push new tag
      env:
        GITHUB_TOKEN: ${{ secrets.TAG_TOKEN }}
      run: |
        new_tag=${{ env.next_tag }}
        git tag $new_tag
        git push origin $new_tag

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TAG_TOKEN }}
      with:
        tag_name: ${{ env.next_tag }}
        release_name: ${{ env.next_tag }}
        body: 'Description of the release'
        draft: false
        prerelease: false
