name: frontend-prod
on:
  workflow_dispatch:
  push:
    # branches:
    #   - uat
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    name: Build and deploy
    #runs-on: [self-hosted, Linux, X64, trumio-orgrunner]
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14.x'

    - name: Install Dependencies and Build
      run: |
        npm install
        npm run build
        
    - name: Deploy to Azure
      uses: TravisSpomer/deploy-to-azure-storage@v1.5.0
      with:
        source-path: dist
        sas-url: ${{ secrets.FE_PROD_SAS_URL }}
