name: frontend-ci-uat
on:
  workflow_dispatch:
  push:
    # branches:
    #   - uat
    tags:
      - 'uat_v*'

env:
  IMAGE_NAME: frontend

jobs:
  frontend-ci-uat:
    runs-on: [self-hosted, Linux, X64, trumio-orgrunner]
    concurrency: release
    permissions:
      id-token: write
      contents: write
################################## TAGGING ##################################################
    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: uat
        submodules: true

    - name: 'Get tag'
      id: tag
      uses: 'WyriHaximus/github-action-get-previous-tag@8a0e045f02c0a3a04e1452df58b90fc7e555e950'

    - name: Set correct environment
      run: |
        TAG=${{ steps.tag.outputs.tag }}
        echo "TAG=$TAG" >> "$GITHUB_ENV"

#####################################  CI  #####################################################
    # Add support for more platforms with QEMU (optional)
    # https://github.com/docker/setup-qemu-action
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Context for Buildx
      id: buildx-context
      run: |
        docker context create builders

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: latest
        endpoint: builders
      
    # login to the ACR
    - name: 'Docker Login'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.UAT_REGISTRY_URL }}
        username: ${{ secrets.UAT_REGISTRY_USERNAME }}
        password: ${{ secrets.UAT_REGISTRY_PASSWORD }}
            
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ${{ secrets.UAT_REGISTRY_URL }}/${{ env.IMAGE_NAME }}

    #build and push to ACR (method1)  for AKS runner  
    - run: |
           docker build -f --no-cache ./Dockerfile -t ${{ secrets.UAT_REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} .
           docker push ${{ secrets.UAT_REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}

    # to update deployment yaml file with proper tag
    - name: Update deployment yml
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: 'manifests/uat/deployment_frontend.yml'
        propertyPath: 'spec.template.spec.containers[0].image'
        value: ${{ secrets.UAT_REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
        branch: uat
        targetBranch: uat

    - run: |
          cat manifests/uat/deployment_frontend.yml
