name: frontend-ci-cd
on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  frontend-ci-cd:
    #if: |
    # startsWith(github.ref, 'refs/tags/uat_v') ||
    # github.event.release.target_commitish == 'uat'
    runs-on: ubuntu-latest
    # runs-on: [self-hosted, linux, X64, trumio-orgrunner]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ vars.BRANCH }}
          submodules: true

      - name: Set manifest folder names
        run: |
          if [[ "${{ vars.ENVIRONMENT }}" == "uat" || "${{ vars.ENVIRONMENT }}" == "tru-uat" || "${{ vars.ENVIRONMENT }}" == "tru-uat-auto" ]]; then
             echo "FOLDER=UAT" >> $GITHUB_ENV
          else
             echo "FOLDER=Prod" >> $GITHUB_ENV
          fi

      - name: Debug TAG variable
        run: echo "TAG is '${{ vars.TAG }}'"

      ## Sharepoint tasks
      - name: Get SharePoint Access Token
        id: get_token
        env:
          CLIENT_ID: ${{ secrets.ENV_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.ENV_CLIENT_SECRET }}
          TENANT_ID: ${{ secrets.ENV_TENANT_ID }}
          SITENAME: Trumio-env
        run: |
          response=$(curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -d "client_id=${{ env.CLIENT_ID }}&client_secret=${{ env.CLIENT_SECRET }}&grant_type=client_credentials&resource=https://graph.microsoft.com" "https://login.microsoftonline.com/${{ env.TENANT_ID }}/oauth2/token")
          echo "token=$(echo $response | jq -r '.access_token')" >> $GITHUB_ENV

      - name: Retrieve Site ID
        id: get_site_id
        run: |
          site_response=$(curl -H "Authorization: Bearer ${{ env.token }}" \
          "https://graph.microsoft.com/v1.0/sites?search=${{ env.SITENAME }}")
          echo "site_id=trumio.sharepoint.com,0702a39f-d261-4be5-b3d4-76525995bc85,b3578a0e-9132-47da-bf61-cc572bf23ced" >> $GITHUB_ENV

      - name: Set SharePoint File Name Based on Tag
        run: |
          if [[ -z "${{ vars.TAG }}" ]]; then
            echo "Error: TAG is empty or undefined."
            exit 1
          elif [[ "${{ vars.TAG }}" == uat_* ]]; then
            echo "FILENAME=env-fe-uat.txt" >> $GITHUB_ENV
          elif [[ "${{ vars.TAG }}" == tru-uat_* ]]; then
            echo "FILENAME=env-fe-tru-uat.txt" >> $GITHUB_ENV            
          elif [[ "${{ vars.TAG }}" == v* ]]; then
            echo "FILENAME=env-fe-prod.txt" >> $GITHUB_ENV
          elif [[ "${{ vars.TAG }}" == tru-prod_* ]]; then
            echo "FILENAME=env-fe-tru-prod.txt" >> $GITHUB_ENV
          else
            echo "Error: Unrecognized environment tag format."
            exit 1
          fi

      - name: Set SharePoint SubFolder Name Based on Tag
        run: |
           if [[ "${{ vars.TAG }}" == uat_* ]]; then
            echo "SUBFOLDER=uat" >> $GITHUB_ENV
           elif [[ "${{ vars.TAG }}" == tru-uat_* ]]; then
            echo "SUBFOLDER=tru-uat" >> $GITHUB_ENV
           elif [[ "${{ vars.TAG }}" == v* ]]; then
            echo "SUBFOLDER=prod" >> $GITHUB_ENV
           elif [[ "${{ vars.TAG }}" == tru-prod_* ]]; then
            echo "SUBFOLDER=tru-prod" >> $GITHUB_ENV
           else
            echo "Error: Unrecognized environment tag format."
            exit 1
           fi

      - name: Fetch Download URL from SharePoint
        id: get_download_url
        run: |
          file_response=$(curl -H "Authorization: Bearer ${{ env.token }}" \
          "https://graph.microsoft.com/v1.0/sites/${{ env.site_id }}/drive/root:/${{ env.FOLDER }}/${{ env.SUBFOLDER }}/${{ env.FILENAME }}")
          echo "File response: $file_response"
          download_url=$(echo $file_response | jq -r '."@microsoft.graph.downloadUrl"')
          echo "Download URL: $download_url"
          echo "download_url=$download_url" >> $GITHUB_ENV

      - name: Display Download URL
        run: |
          echo "Download URL:"
          echo "${{ env.download_url }}"

      - name: Download File from SharePoint
        run: |
          if [ -z "${{ env.download_url }}" ]; then
            echo "Error: Download URL is empty"
            exit 1
          fi
          curl -L "${{ env.download_url }}" --output secrets.txt
          echo "File downloaded successfully."

      - name: Copy output to env file and display
        run: |
          if [[ "${{ vars.ENVIRONMENT }}" == "uat" ]]; then
              cp secrets.txt .env.uat.local
          elif [[ "${{ vars.ENVIRONMENT }}" == "tru-uat" ]]; then
              cp secrets.txt .env.tru-uat.local
          elif [[ "${{ vars.ENVIRONMENT }}" == "prod" ]]; then
              cp secrets.txt .env.production.local
          elif [[ "${{ vars.ENVIRONMENT }}" == "tru-prod" ]]; then
              cp secrets.txt .env.tru-production.local
          else
              echo "Error: Invalid environment."
              exit 1
          fi
        shell: bash

      - name: Install Azure cli
        run: |
          sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
          curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
          AZ_REPO=$(lsb_release -cs)
          echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
          sudo apt-get update
          sudo apt-get install azure-cli

      - name: Set Azure environment
        id: azure
        run: |
          if [[ "${{ vars.ENVIRONMENT }}" == "uat" || "${{ vars.ENVIRONMENT }}" == "tru-uat" ]]; then
              echo "azure_clientid=${{ secrets.AZURE_CLIENT_ID_UAT }}" >> $GITHUB_ENV
              echo "azure_tenantid=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
              echo "azure_subscriptionid=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
              echo "azure_clientsecret=${{ secrets.AZURE_CLIENT_SECRET_UAT }}" >> $GITHUB_ENV
          else
              echo "azure_clientid=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
              echo "azure_tenantid=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
              echo "azure_subscriptionid=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
              echo "azure_clientsecret=${{ secrets.AZURE_CLIENT_SECRET }}" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ env.azure_clientid }}","clientSecret":"${{ env.azure_clientsecret }}","subscriptionId":"${{ env.azure_subscriptionid }}","tenantId":"${{ env.azure_tenantid }}"}'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Set environment variable
        run: |
          if [[ "${{ vars.ENVIRONMENT }}" == "uat" ]]; then
              echo "VITE_ENV_MODE=uat" >> $GITHUB_ENV
              echo "storage=azusctruatwebsa" >> $GITHUB_ENV
              echo "backup_directory=uat-frontend-backup" >> $GITHUB_ENV
              echo "cdn_endpoint=trumiouatfdcdn" >> $GITHUB_ENV
              echo "cdn_domain=uat.trumio.ai" >> $GITHUB_ENV

          elif [[ "${{ vars.ENVIRONMENT }}" == tru-uat ]]; then
              echo "VITE_ENV_MODE=tru-uat" >> $GITHUB_ENV
              echo "storage=azusctrtruuatwebsa" >> $GITHUB_ENV
              echo "backup_directory=tru-uat-frontend-backup" >> $GITHUB_ENV
              echo "cdn_endpoint=trumio-tru-uat-fdcdn" >> $GITHUB_ENV
              echo "cdn_domain=tru-uat.trumio.ai" >> $GITHUB_ENV

          elif [[ "${{ vars.ENVIRONMENT }}" == prod ]]; then
              echo "VITE_ENV_MODE=production" >> $GITHUB_ENV
              echo "storage=azusctrwebsa" >> $GITHUB_ENV
              echo "backup_directory=prod-frontend-backup" >> $GITHUB_ENV
              echo "cdn_endpoint=trumioprodcdn" >> $GITHUB_ENV
              echo "cdn_domain=app.trumio.ai" >> $GITHUB_ENV

          elif [[ "${{ vars.ENVIRONMENT }}" == tru-prod ]]; then
              echo "VITE_ENV_MODE=tru-production" >> $GITHUB_ENV
              echo "storage=azusctrtruprodwebsa" >> $GITHUB_ENV
              echo "backup_directory=tru-prod-frontend-backup" >> $GITHUB_ENV
              echo "cdn_endpoint=trumio-tru-prod-fdcdn" >> $GITHUB_ENV
              echo "cdn_domain=tru-app.trumio.ai" >> $GITHUB_ENV
          fi

      - name: Echo VITE variable
        run: echo ${{ env.VITE_ENV_MODE }}

      - name: Install Dependencies
        run: |
          npm install --legacy-peer-deps && npm install --save env-cmd --legacy-peer-deps

      - name: NPM Build
        run: |
          npm run build -- --mode ${{ env.VITE_ENV_MODE }}

      - name: Upload to blob storage
        run: |
          today=$(date +%d-%m-%Y-%H.%M)
          az storage blob upload-batch --account-name ${{ env.storage }} --auth-mode login -d "${{ env.backup_directory }}/frontend-$today" --source ./dist

      - name: Delete blob storage
        run: az storage blob delete-batch --account-name ${{ env.storage }} --auth-mode login --source '$web' --pattern '*'

      - name: Upload to blob storage
        run: az storage blob upload-batch --account-name ${{ env.storage }} --auth-mode login -d '$web' --source ./dist

      - name: Purge CDN endpoint
        run: az afd endpoint purge --resource-group azusctr-rg --profile-name azusctr-cdn --endpoint-name ${{ env.cdn_endpoint }} --domains ${{ env.cdn_domain }} --content-paths '/*'

      # Azure logout
      - name: logout
        run: |
          az logout
        if: always()
