name: frontend-ci-cd-maintenance site configuration
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "select environment for maintenance site configuration"
        required: true
        type: choice
        options:
          - uat
          - tru-uat
          - tru-uat-auto
          - tru-lti
          - tru-wipro
          - tru-prod
          - prod

jobs:
  frontend-ci-cd-maintenace:
    runs-on: ubuntu-latest
    concurrency: release
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          #ref: ${{ vars.BRANCH }}
          submodules: true
      - name: Set Azure Static Web Apps Token
        run: |
          if [[ "${{ github.event.inputs.environment }}" == "tru-uat" ]]; then
            echo "AZURE_STATIC_WEB_APPS_API_TOKEN=${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_TRU_TEST }}" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.environment }}" == "tru-uat-auto" ]]; then
            echo "AZURE_STATIC_WEB_APPS_API_TOKEN=${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_TRU_UAT_AUTO }}" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.environment }}" == "tru-wipro" ]]; then
            echo "AZURE_STATIC_WEB_APPS_API_TOKEN=${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_TRU_WIPRO }}" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.environment }}" == "uat" ]]; then
            echo "AZURE_STATIC_WEB_APPS_API_TOKEN=${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_UAT }}" >> $GITHUB_ENV    
          elif [[ "${{ github.event.inputs.environment }}" == "tru-prod" ]]; then
            echo "AZURE_STATIC_WEB_APPS_API_TOKEN=${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_TRU_PROD }}" >> $GITHUB_ENV 
          elif [[ "${{ github.event.inputs.environment }}" == "prod" ]]; then
            echo "AZURE_STATIC_WEB_APPS_API_TOKEN=${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROD }}" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.environment }}" == "tru-lti" ]]; then
            echo "AZURE_STATIC_WEB_APPS_API_TOKEN=${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_TRU_LTI }}" >> $GITHUB_ENV
          else
            echo "Error: Unrecognized environment "
            exit 1
          fi

      - name: Static Webapp Deployment 
        id: webapp_deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          skip_api_build: true
          skip_app_build: true
          app_location: '/custom'
          output_location: ''
          is_static_export: true

      # Azure logout
      - name: logout
        run: |
          az logout
        if: always()
