name: SonarQube-Analysis
 
on:
  push:
    branches:
      - tru-dev
      - pilot/project-hackathon 
  # pull_request:
  #   branches:
  #     - main
 
jobs:
  sonarqube-analysis:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
 
    steps:
      #Checking out repository
      - uses: actions/checkout@v4
 
      # Python environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
 
      #Dependencies installation
      - name: Install dependencies
        run: npm install
 
      # SonarCloud scan
      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npx sonarqube-scanner \
            -Dsonar.projectKey=trumio_trumio-web-react \
            -Dsonar.organization=trumio \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.branch.name=${{ github.ref_name }}
