# name: SonarQube-Analysis

# on:
#   push:
#     branches:
#       - tru-dev
#       - pilot/project-hackathon
#   pull_request:
#     branches:
#       - tru-dev

# jobs:
#   sonarqube-analysis:
#     name: SonarQube Analysis
#     runs-on: ubuntu-latest

#     steps:
#       #Checking out repository
#       - uses: actions/checkout@v4

#       # Python environment
#       - name: Set up Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: '18.x'

#       #Dependencies installation
#       - name: Install dependencies
#         run: |
#           npm install --legacy-peer-deps && npm install --save env-cmd --legacy-peer-deps
#         # npm install -g sonarqube-scanner

#       - name: SonarQube Scan
#         uses: SonarSource/sonarqube-scan-action@v4
#         with:
#           args: >
#             -Dsonar.organization=trumio
#             -Dsonar.projectKey=trumio_trumio-web-react
#             -Dsonar.sources=.
#             -Dsonar.host.url=https://sonarcloud.io 
#             -Dsonar.token=$SONAR_TOKEN 
#             -Dsonar.branch.name=${{ github.ref_name }}
#         env:
#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

#       # # SonarQube Analysis
#       # - name: SonarCloud Scan
#       #   env:
#       #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#       #   run: |
#       #     npx sonarqube-scanner \
#       #       -Dsonar.projectKey=trumio_trumio-web-react \
#       #       -Dsonar.organization=trumio \
#       #       -Dsonar.sources=. \
#       #       -Dsonar.host.url=https://sonarcloud.io \
#       #       -Dsonar.token=$SONAR_TOKEN \
#       #       -Dsonar.branch.name=${{ github.ref_name }}


name: SonarQube-Analysis

on:
  push:
    branches:
      - tru-dev
      - pilot/project-hackathon
  pull_request:
    branches:
      - tru-dev

jobs:
  sonarqube-analysis:
    name: SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      # Checking out repository
      - uses: actions/checkout@v4

      # Python environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      #Dependencies installation
      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps && npm install --save env-cmd --legacy-peer-deps

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        with:
          args: >
            -Dsonar.organization=trumio
            -Dsonar.projectKey=trumio_trumio-web-react
            -Dsonar.sources=.
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.token=$SONAR_TOKEN
            -Dsonar.branch.name=${{ github.ref_name }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

