name: SonarQube-Analysis
 
on:
  push:
    branches:
      - pilot/project-hackathon 
  # pull_request:
  #   branches:
  #     - main
 
jobs:
  sonarqube-analysis:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
 
    steps:
      #Checking out repository
      - uses: actions/checkout@v4
        # with:
        #   fetch-depth: 0
        #   ref: pilot/project-hackathon
 
      # Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9 
 
      #Dependencies installation
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
          pip install pysonar-scanner
 
      # SonarCloud scan
      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          pysonar-scanner \
            -Dsonar.projectKey=trumio_trumio-user-management-be \
            -Dsonar.organization=trumio \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.branch.name=${{ github.ref_name }}
