export enum MilestoneDetailsModalType {
  // Milestone level modals
  CONFIRM_ACCEPT_MILESTONE = 'CONFIRM_ACCEPT_MILESTONE',
  CONFIRM_SUBMIT_MILESTONE = 'CONFIRM_SUBMIT_MILESTONE',
  MILESTONE_ACCEPTED = 'MILESTONE_ACCEPTED',
  MILESTONE_SUBMITTED = 'MILESTONE_SUBMITTED',

  // Artifacts level modals
  CONFIRM_REMOVE_ARTIFACT = 'CONFIRM_REMOVE_ARTIFACT',
  ARTIFCAT_REMOVED = 'ARTIFCAT_REMOVED',
}
