export enum MilestoneDetailsModalType {
  // Milestone level modals
  CONFIRM_ACCEPT_MILESTONE = 'CONFIRM_ACCEPT_MILESTONE',
  CONFIRM_SUBMIT_MILESTONE = 'CONFIRM_SUBMIT_MILESTONE',
  MILESTONE_ACCEPTED = 'MILESTONE_ACCEPTED',
  MILESTONE_SUBMITTED = 'MILESTONE_SUBMITTED',

  // Artifacts level modals
  CONFIRM_REMOVE_ARTIFACT = 'CONFIRM_REMOVE_ARTIFACT',
  ARTIFACT_REMOVED = 'ARTIFACT_REMOVED',
  CONFIRM_ARTIFACTS_SUBMISSION = 'CONFIRM_ARTIFACTS_SUBMISSION',
  ARTIFCATS_SUBMITTED = 'ARTIFCATS_SUBMITTED',
  ARTIFACTS_DRAFT_SAVED = 'ARTIFACTS_DRAFT_SAVED',
}

export enum MilestoneDropdownOptions {
  GIVE_RECOGNITION = 'GIVE_RECOGNITION',
  VIEW_RECOGNITION = 'VIEW_RECOGNITION',
}
